
services:
  lineten:
    hostname: lineten
    container_name: lineten
    depends_on: 
      - db
    image: lineten
    # build: .
    # command: node index.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - lineten
  
  db:
    hostname: db
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    networks: 
      - lineten

networks: 
  lineten:
    driver: bridge